/**
 * Smart Contract ABIs
 *
 * Application Binary Interfaces for Ethereum contracts.
 * These are generated by the Solidity compiler (hardhat/foundry).
 *
 * Per Constitution Principle II: Blockchain-First Architecture
 * ABIs define the exact interface between frontend and smart contracts.
 *
 * NOTE: These placeholder ABIs should be replaced with actual ABIs
 * generated from compiled Solidity contracts. For now, they show the expected structure.
 */

/**
 * GovernanceProposal Contract ABI
 * Main contract for proposal creation and voting
 *
 * Generated from: contracts/GovernanceProposal.sol
 * Solidity version: ^0.8.0
 */
export const GOVERNANCE_PROPOSAL_ABI = [
  // Constructor
  {
    type: "constructor",
    inputs: [
      {
        name: "_governanceToken",
        type: "address",
        internalType: "contract IERC20Snapshot",
      },
      {
        name: "_forwarder",
        type: "address",
        internalType: "address",
      },
    ],
  },

  // Events
  {
    type: "event",
    name: "ProposalCreated",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "title",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "votingDeadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "snapshotBlock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },

  {
    type: "event",
    name: "VoteCast",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "choice",
        type: "uint8",
        indexed: false,
        internalType: "enum VoteChoice",
      },
      {
        name: "votingPower",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },

  {
    type: "event",
    name: "ProposalStatusChanged",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "oldStatus",
        type: "uint8",
        indexed: false,
        internalType: "enum ProposalStatus",
      },
      {
        name: "newStatus",
        type: "uint8",
        indexed: false,
        internalType: "enum ProposalStatus",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },

  {
    type: "event",
    name: "VotingDeadlineReached",
    inputs: [
      {
        name: "proposalId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "forVotes",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "againstVotes",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "abstainVotes",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },

  // State variables (read-only)
  {
    type: "function",
    name: "proposalCount",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "VOTING_PERIOD",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  // Write functions
  {
    type: "function",
    name: "createProposal",
    inputs: [
      {
        name: "_title",
        type: "string",
        internalType: "string",
      },
      {
        name: "_description",
        type: "string",
        internalType: "string",
      },
      {
        name: "_targetAction",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "proposalId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },

  {
    type: "function",
    name: "castVote",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_choice",
        type: "uint8",
        internalType: "enum VoteChoice",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },

  {
    type: "function",
    name: "castVoteGasless",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_choice",
        type: "uint8",
        internalType: "enum VoteChoice",
      },
      {
        name: "_signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },

  {
    type: "function",
    name: "activateProposal",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },

  {
    type: "function",
    name: "closeProposal",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },

  // Read functions
  {
    type: "function",
    name: "getProposal",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Proposal",
        components: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "title",
            type: "string",
            internalType: "string",
          },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
          {
            name: "targetAction",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "snapshotBlock",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "votingDeadline",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum ProposalStatus",
          },
          {
            name: "createdAt",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "forVotes",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "againstVotes",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "abstainVotes",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "getVotingResults",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "forVotes",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "againstVotes",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "abstainVotes",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "hasVoted",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_voter",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "getVote",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_voter",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "choice",
        type: "uint8",
        internalType: "enum VoteChoice",
      },
      {
        name: "votingPower",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "getProposalStatus",
    inputs: [
      {
        name: "_proposalId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum ProposalStatus",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "getVotingPowerAtBlock",
    inputs: [
      {
        name: "_member",
        type: "address",
        internalType: "address",
      },
      {
        name: "_blockNumber",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
];

/**
 * EIP712VotingForwarder Contract ABI
 * Gasless meta-transaction relayer
 *
 * Generated from: contracts/EIP712VotingForwarder.sol
 * Solidity version: ^0.8.0
 */
export const EIP712_VOTING_FORWARDER_ABI = [
  // Events
  {
    type: "event",
    name: "MetaTransactionExecuted",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "data",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
      {
        name: "signature",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
  },

  // Write functions
  {
    type: "function",
    name: "executeMetaTx",
    inputs: [
      {
        name: "_from",
        type: "address",
        internalType: "address",
      },
      {
        name: "_to",
        type: "address",
        internalType: "address",
      },
      {
        name: "_data",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "_signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "success",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "returnData",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    stateMutability: "payable",
  },

  // Read functions
  {
    type: "function",
    name: "getNonce",
    inputs: [
      {
        name: "_user",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "verify",
    inputs: [
      {
        name: "_from",
        type: "address",
        internalType: "address",
      },
      {
        name: "_to",
        type: "address",
        internalType: "address",
      },
      {
        name: "_data",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "_signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "valid",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
];

/**
 * ERC20Snapshot Contract ABI (partial)
 * Standard ERC20 token with snapshot capability for voting power history
 */
export const ERC20_SNAPSHOT_ABI = [
  {
    type: "function",
    name: "balanceOf",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "balanceOfAt",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "snapshotId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "function",
    name: "totalSupplyAt",
    inputs: [
      {
        name: "snapshotId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },

  {
    type: "event",
    name: "Transfer",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },

  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
  },
];
